name: Continuous Integration - Non-Main Branches

on:
  push:
    branches-ignore:
      - 'main'  

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Run unit tests
        run: mvn test -Dtest=FilmServiceUnitTest 
        
      - name: Run integration tests
        run: mvn test -Dtest=FilmServiceIntegrationTest 
