name: Continuous integration - Workflow4

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
    
jobs:
  system-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        browser: [chrome, edge, safari]
        
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
           distribution: 'temurin'
           java-version: '17'

      - name: Run system test
        run: |
          if (${{ matrix.os }} -eq 'ubuntu-latest') {
            if (${{ matrix.browser }} -eq 'chrome') {
              mvn test -Dtest=FilmUITest -Dos=${{ matrix.os }} -Dbrowser=${{ matrix.browser }}
            }
          }
          
          if (${{ matrix.os }} -eq 'windows-latest') {
            if (${{ matrix.browser }} -eq 'chrome') {
              mvn test -Dtest=FilmUITest -Dos=${{ matrix.os }} -Dbrowser=${{ matrix.browser }}
            }
            if (${{ matrix.browser }} -eq 'edge') {
              mvn test -Dtest=FilmUITest -Dos=${{ matrix.os }} -Dbrowser=${{ matrix.browser }}
            }
          }
          
          if (${{ matrix.os }} -eq 'macos-latest') {
            if (${{ matrix.browser }} -eq 'chrome') {
              mvn test -Dtest=FilmUITest -Dos=${{ matrix.os }} -Dbrowser=${{ matrix.browser }}
            }
            if (${{ matrix.browser }} -eq 'safari') {
              mvn test -Dtest=FilmUITest -Dos=${{ matrix.os }} -Dbrowser=${{ matrix.browser }}
            }
          }

