name: Continuous integration - Workflow1

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run unit test
        run: mvn test -Dtest=FilmServiceUnitaryTest

      - name: Run unit test 2
        run: mvn test -Dtest=FilmServiceTest
        
      - name: Run integration test
        run: mvn test -Dtest=UrlUtilsIntegrationTest

      - name: Run integration test 2
        run: mvn test -Dtest=UrlUtilsTest
