name: Continuous integration - Workflow4

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
    
jobs:
  system-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        browser: [chrome, edge, safari]
        
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
           distribution: 'temurin'
           java-version: '17'

      - name: Run system test
        run: |
          if [[ ${{ matrix.os }} == 'ubuntu-latest' ]]; then
            if [[ ${{ matrix.browser }} == 'chrome' ]]; then
              mvn test -Dtest=FilmUITest -Dos=${{ matrix.os }} -Dbrowser=${{ matrix.browser }}
            fi
          fi
          
          if [[ ${{ matrix.os }} == 'windows-latest' ]]; then
            if [[ ${{ matrix.browser }} == 'chrome' ]]; then
              mvn test -Dtest=FilmUITest -Dos=${{ matrix.os }} -Dbrowser=${{ matrix.browser }}
            fi
            if [[ ${{ matrix.browser }} == 'edge' ]]; then
              mvn test -Dtest=FilmUITest -Dos=${{ matrix.os }} -Dbrowser=${{ matrix.browser }}
            fi
          fi
          
          if [[ ${{ matrix.os }} == 'macos-latest' ]]; then
            if [[ ${{ matrix.browser }} == 'chrome' ]]; then
              mvn test -Dtest=FilmUITest -Dos=${{ matrix.os }} -Dbrowser=${{ matrix.browser }}
            fi
            if [[ ${{ matrix.browser }} == 'safari' ]]; then
              mvn test -Dtest=FilmUITest -Dos=${{ matrix.os }} -Dbrowser=${{ matrix.browser }}
            fi
          fi
