name: Continuous integration - Workflow1

on:
  push:
    branches:
      - '!main'

jobs:
  unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'

      - name: Build and run unit tests
        run: run mvn -Dtest= FilmServiceTest

  integration_tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'

      - name: Build and run integration tests
        run: mvn test
