name: Pre-Merge Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run integration test
        run: mvn test -Dtest=UrlUtilsTest

      - name: Run integration test 2
        run: mvn test -Dtest=UrlUtilsIntegrationTest


